# Generated by Django 4.1.2 on 2022-10-16 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsm_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='posted_by',
            new_name='assigned_to',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='created',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='memo',
            new_name='task',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='created',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='date_completed',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='important',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='title',
        ),
        migrations.AddField(
            model_name='todo',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='todos',
            field=models.ManyToManyField(blank=True, to='jsm_app.todo'),
        ),
    ]
