# Generated by Django 4.1.2 on 2022-10-16 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jsm_app', '0002_rename_posted_by_todo_assigned_to_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='todos',
        ),
        migrations.AddField(
            model_name='user',
            name='todos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jsm_app.todo'),
        ),
    ]
